# Generated by Django 4.1 on 2023-03-22 16:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("game", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="character",
            name="backstory",
            field=models.CharField(max_length=2000),
        ),
    ]
